name: Generate Snake

on:
  # Runs at 00:00 UTC every day
  schedule:
    - cron: "0 0 * * *"
  
  # Allows manual trigger from Actions tab
  workflow_dispatch:
  
  # Runs on every push to main
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Generate the snake
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: Harsimran-singh-7765
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=#58a6ff&color_dots=#0d1117,#161b22,#21262d,#30363d,#484f58

      # Push the generated files
      - name: Push github-contribution-grid-snake.svg
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}